# Generated by Django 4.2.6 on 2023-10-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_course_content_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='course_obj',
        ),
        migrations.AlterField(
            model_name='course_content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
    ]
