# Generated by Django 4.2.6 on 2023-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_client_client_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_content',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
