# Generated by Django 4.2.6 on 2023-10-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_course_description_course_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
