# Generated by Django 4.2.6 on 2023-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_client_email_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
