# Generated by Django 4.2.6 on 2023-10-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
